"""Initial

Revision ID: d60a3673d564
Revises: 
Create Date: 2025-05-08 15:57:52.828015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60a3673d564'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('tag_ids', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('date_open', sa.DateTime(), nullable=False),
    sa.Column('date_close', sa.DateTime(), nullable=True),
    sa.Column('balance_beginning', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category_types',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_types_name'), ['name'], unique=True)

    op.create_table('institutions',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tag_ids', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction_statuses',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_statuses_name'), ['name'], unique=True)

    op.create_table('transaction_types',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_types_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('pass_hash', sa.String(length=256), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('transaction_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_types_name'))

    op.drop_table('transaction_types')
    with op.batch_alter_table('transaction_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_statuses_name'))

    op.drop_table('transaction_statuses')
    op.drop_table('institutions')
    with op.batch_alter_table('category_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_types_name'))

    op.drop_table('category_types')
    op.drop_table('accounts')
    # ### end Alembic commands ###
